Removing outputing summary_hints(they are causing strange error like: AttributeError: RerunInfoTerminalReporter instance has no attribute 'summary_hints' )